In [2]:
import numpy as np
import random as rd
from main import sigmoid, init_layers

[array([[-0.14945419, -0.38980819,  0.31934125],
       [ 0.13828888,  0.15244925, -1.36137805]]), array([[ 0.04160768, -0.31721   ],
       [-1.66324761, -0.48573082]])]
[array([[0.],
       [0.],
       [0.]]), array([[1.23039298],
       [0.21530894]]), array([[-7.53255582e-04],
       [ 9.65606045e-01]])]


In [8]:
# Testing how to access each value in a list of arrays
W, b = init_layers(3, [3, 2, 2])
print(W)
print(W[0])
print(W[0][0])
print(W[0][0][0])

[array([[ 1.52998102, -0.68717807, -0.29929905],
       [ 1.13779039,  0.22411623,  0.11532783]]), array([[-0.4570127 ,  1.3221232 ],
       [ 0.39330588, -0.83539146]])]
[[ 1.52998102 -0.68717807 -0.29929905]
 [ 1.13779039  0.22411623  0.11532783]]
[ 1.52998102 -0.68717807 -0.29929905]
1.5299810179853108


In [3]:
L = 3
neurons = [3, 2, 2]
X = np.array([[1.], [2.], [3.]])

W = [np.array([[ 0.06343915,  1.56121565,  0.60868435],
       [-0.84027574, -0.28201683, -1.79479978]]), np.array([[-0.17793126, -0.4172283 ],
       [-0.30004577, -0.09681589]])]
b = [np.array([[0.],
       [0.],
       [0.]]), np.array([[0.48079775],
       [1.38557334]]), np.array([[-0.76150554],
       [-0.38210952]])]


A = [0 for i in range(L)]
A[0] = X.T
Z = [0 for i in range(0, L)]
Z[0] = A[0]

print(A[0].shape)
print(W[0].shape)

""" for i in range(1, len(W)+1):
       Z[i] = W[i-1] @ A[i-1] + b[i]
       A[i] = sigmoid(Z[i]) """

# This allows us to identify the problem : X.T leads to an matrix multiplication issue.

A[0] = X

test = [0 for i in range(L)]
test[0] = Z[0]


for i in range(1, len(W)+1):
       Z[i] = W[i-1] @ A[i-1] + b[i]
       test.append(W[i-1] @ A[i-1] + b[i])
       A[i] = sigmoid(Z[i])

print(A[1])
print(A[2])

print("------------")
print("List of Matrix A")
print(A)
print("------------")
print("List of Matrix Z")
print(Z)
print("------------")
print("List of Matrix Z_test")
print(test)
print("------------")
print("List of Matrix W")
print(W)
print("------------")
print("List of Matrix b")
print(b)


print("len b: ", len(b))


(1, 3)
(2, 3)
[[0.99590025]
 [0.00448226]]
[[0.28078371]
 [0.33595803]]
------------
List of Matrix A
[array([[1.],
       [2.],
       [3.]]), array([[0.99590025],
       [0.00448226]]), array([[0.28078371],
       [0.33595803]])]
------------
List of Matrix Z
[array([[1., 2., 3.]]), array([[ 5.49272125],
       [-5.4031354 ]]), array([[-0.94057745],
       [-0.68135913]])]
------------
List of Matrix Z_test
[array([[1., 2., 3.]]), 0, 0, array([[ 5.49272125],
       [-5.4031354 ]]), array([[-0.94057745],
       [-0.68135913]])]
------------
List of Matrix W
[array([[ 0.06343915,  1.56121565,  0.60868435],
       [-0.84027574, -0.28201683, -1.79479978]]), array([[-0.17793126, -0.4172283 ],
       [-0.30004577, -0.09681589]])]
------------
List of Matrix b
[array([[0.],
       [0.],
       [0.]]), array([[0.48079775],
       [1.38557334]]), array([[-0.76150554],
       [-0.38210952]])]
len b:  3


In [10]:


# Limited to 10 layers - 10 layers probably won't ever be need in our case and we don't have infinite calculation power
L = rd.randint(1, 10)

dims = []
for i in range(L):
    dims.append(rd.randint(1, 10))

n1 = dims[0]

X_list = []
for i in range(n1):
    X_list.append([rd.randint(1, 200)])

X = np.array(X_list)

print(type(X))
print(X)
print()
print(dims)

<class 'numpy.ndarray'>
[[137]]

[1, 8, 10, 6, 2, 4, 4]
