In [1]:
import numpy as np
import random as rd
from main import sigmoid, init_layers

In [22]:
# Testing how to access each value in a list of arrays
W, b = init_layers(3, [3, 2, 2])
print(W)
print(W[0])
print(W[0][0])
print(W[0][0][0])

[array([[-0.56514293, -1.42720124,  0.93803855],
       [ 1.36782645, -0.0104528 , -1.27541837]]), array([[-0.7557488 ,  0.35374417],
       [-0.2166184 , -0.37544494]])]
[[-0.56514293 -1.42720124  0.93803855]
 [ 1.36782645 -0.0104528  -1.27541837]]
[-0.56514293 -1.42720124  0.93803855]
-0.5651429299191095


In [21]:
L = 3
neurons = [3, 2, 2]
X = np.array([[1.], [2.], [3.]])

W = [np.array([[ 0.06343915,  1.56121565,  0.60868435],
       [-0.84027574, -0.28201683, -1.79479978]]), np.array([[-0.17793126, -0.4172283 ],
       [-0.30004577, -0.09681589]])]
b = [np.array([[0.],
       [0.],
       [0.]]), np.array([[0.48079775],
       [1.38557334]]), np.array([[-0.76150554],
       [-0.38210952]])]


A = [0 for i in range(L)]
A[0] = X.T
Z = [0 for i in range(0, L)]
Z[0] = A[0]

print(A[0].shape)
print(W[0].shape)

""" for i in range(1, len(W)+1):
       Z[i] = W[i-1] @ A[i-1] + b[i]
       A[i] = sigmoid(Z[i]) """

# This allows us to identify the problem : X.T leads to an matrix multiplication issue.

A[0] = X

test = [0 for i in range(L)]
test[0] = Z[0]


for i in range(1, len(W)+1):
       Z[i] = W[i-1] @ A[i-1] + b[i]
       test.append(W[i-1] @ A[i-1] + b[i])
       A[i] = sigmoid(Z[i])

print(A[1])
print(A[2])

print("------------")
print("List of Matrix A")
print(A)
print("------------")
print("List of Matrix Z")
print(Z)
print("------------")
print("List of Matrix Z_test")
print(test)
print("------------")
print("List of Matrix W")
print(W)
print("------------")
print("List of Matrix b")
print(b)


print("len b: ", len(b))


(1, 3)
(2, 3)
[[0.99590025]
 [0.00448226]]
[[0.28078371]
 [0.33595803]]
------------
List of Matrix A
[array([[1.],
       [2.],
       [3.]]), array([[0.99590025],
       [0.00448226]]), array([[0.28078371],
       [0.33595803]])]
------------
List of Matrix Z
[array([[1., 2., 3.]]), array([[ 5.49272125],
       [-5.4031354 ]]), array([[-0.94057745],
       [-0.68135913]])]
------------
List of Matrix Z_test
[array([[1., 2., 3.]]), 0, 0, array([[ 5.49272125],
       [-5.4031354 ]]), array([[-0.94057745],
       [-0.68135913]])]
------------
List of Matrix W
[array([[ 0.06343915,  1.56121565,  0.60868435],
       [-0.84027574, -0.28201683, -1.79479978]]), array([[-0.17793126, -0.4172283 ],
       [-0.30004577, -0.09681589]])]
------------
List of Matrix b
[array([[0.],
       [0.],
       [0.]]), array([[0.48079775],
       [1.38557334]]), array([[-0.76150554],
       [-0.38210952]])]
len b:  3


In [20]:


# Limited to 10 layers - 10 layers probably won't ever be need in our case and we don't have infinite calculation power
L = rd.randint(1, 10)

dims = []
for i in range(L):
    dims.append(rd.randint(1, 10))

n1 = dims[0]

X_list = []
for i in range(n1):
    X_list.append([rd.randint(1, 200)])

X = np.array(X_list)

print(type(X))
print(X)
print()
print(dims)

<class 'numpy.ndarray'>
[[ 97]
 [104]
 [ 82]
 [ 73]
 [113]
 [105]
 [194]
 [190]
 [ 46]
 [ 24]]

[10, 10, 4, 6]


In [23]:
print(X)
print(X.shape)

[[1.]
 [2.]
 [3.]]
(3, 1)


## Tests on Matrix multiplication 

In [30]:
from main import init_layers

W, b = init_layers(3, [3, 2, 2])

In [31]:
print("W: ", W)
print("b: ", b)

W:  [array([[ 0.007704  , -1.40124616, -0.5297211 ],
       [ 1.41261942, -0.83241364, -0.14795384]]), array([[-0.82918784, -0.80106936],
       [-0.19199671, -0.47419383]])]
b:  [array([[0.],
       [0.],
       [0.]]), array([[-0.07059285],
       [-0.76018353]]), array([[1.39330049],
       [2.58360113]])]


In [34]:
for i in range(len(W)):
    print(W[i].shape)

print("-------------")

for i in range(len(b)):
    print(b[i].shape)

(2, 3)
(2, 2)
-------------
(3, 1)
(2, 1)
(2, 1)


In [70]:
X1 = np.array([[1, 2, 3],
      [2, 3, 4],
      [3, 4, 5]])

print(type(X1))
print(X1.shape)

X2 = X1.T
print(type(X2))
print(X2.shape)

<class 'numpy.ndarray'>
(3, 3)
<class 'numpy.ndarray'>
(3, 3)


In [66]:
print(W[0].shape)

(2, 3)


In [71]:
from main import sigmoid

assert len(X1[0] ) == len(W[0][1])
    

A = [0 for i in range(3)]
A[0] = X2
Z = [0 for i in range(0, 3)]
Z[0] = A[0]

for i in range(1, 3):
    Z[i] = W[i-1] @ A[i-1] + b[i]
    A[i] = sigmoid(Z[i])

print(A[-1].shape)
print(A[-1])
print(type(A[-1]))

(2, 3)
[[0.77422724 0.76498603 0.75170508]
 [0.92356162 0.92114236 0.91793611]]
<class 'numpy.ndarray'>


In [52]:
from main import sigmoid

assert len(X1[0] ) == len(W[0][1])
    

A = [0 for i in range(3)]
A[0] = X1
Z = [0 for i in range(0, 3)]
Z[0] = A[0]

for i in range(1, 3):
    Z[i] = W[i-1].dot(A[i-1]) + b[i]
    A[i] = sigmoid(Z[i])

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)